plugins {
    id 'multiloader-fabric'
}

repositories {
    mavenLocal()
}

dependencies {
    modImplementation("io.ejekta.percale:percale-fabric:${percale_version}")
    include("io.ejekta.percale:percale-fabric:${percale_version}")
    modRuntimeOnly "com.terraformersmc:modmenu:${mod_menu_version}"
}
