modLoader = "kotlinforforge"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/ejektaflex/Kambrik/issues"
license = "GPL 3.0"

[[mods]]
modId = "kambrik"
version = "${version}"
displayName = "Kambrik"
authors = "Ejektaflex"
description = '''
A Lightweight Kotlin Library Mod!
'''
#logoFile = ""

[[mixins]]
config = "kambrik.mixins.json"

[[dependencies.kambrik]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.kambrik]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"
