plugins {
    id 'multiloader-neoforge'
}

repositories {
    mavenLocal()
}

dependencies {
    def localPercaleNeo = rootProject.file("../Percale/neoforge/build/libs/percale-neoforge-${percale_version}.jar")
    if (localPercaleNeo.exists()) {
        implementation(files(localPercaleNeo))
        jarJar(files(localPercaleNeo))
    } else {
        implementation("io.ejekta.percale:percale-neoforge:${percale_version}")
        jarJar("io.ejekta.percale:percale-neoforge:${percale_version}")
    }
}
